version: "3.10"
   
services:
    django:
        build: .
        container_name: django
        restart: always
        command: >
            sh -c   "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        expose:
            - 8000
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        depends_on:
            - pgdb
            - redis
            - rabbitmq
    worker1:
        build: .
        restart: always
        environment:
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        command: celery -A core.celery worker -l info -Q parse_queue -E
        volumes:
            - .:/usr/src/app
        links:
            - rabbitmq
        depends_on:
            - redis
            - rabbitmq
    worker2:
        build: .
        restart: always
        environment:
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        command: celery -A core.celery worker -l info -Q download_queue -E 
        volumes:
            - .:/usr/src/app
        links:
            - rabbitmq
        depends_on:
            - redis
            - rabbitmq
    pgdb:
        image: postgres
        container_name: pgdb
        ports:
            - 5432:5432
        expose:
            - 5432
        environment:
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        container_name: redis
        command: redis-server
        ports:
            - 6379:6379
        expose:
            - 6379
    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: rabbitmq
        command: rabbitmq-server
        ports:
            - 5672:5672
            - 15672:15672
        expose:
            - 5672
    flower:
        image: mher/flower
        build: .
        restart: always
        command: ['celery', '--broker=${CELERY_BROKER_URL}', 'flower',]
        ports:
            - 5555:5555
        expose:
            - 5555
        environment:
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        depends_on:
            - redis
            - rabbitmq
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
volumes:
    pgdata:
