version: "3.10"
   
services:
    django:
        build: .
        expose:
            - "8000"
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        depends_on:
            - pgdb
            - redis
            - rabbitmq
    celery:
        image: celery
        restart: always
        build: .
        command: bash -c 'celery -A core.celery worker -l info -Q download_queue &&
                        celery -A core.celery worker -l info -Q parse_queue'
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - pgdb
            - django
            - redis
            - rabbitmq
    pgdb:
        image: postgres
        container_name: pgdb
        ports:
            - "5432:5432"
        expose:
            - "5432"
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
            - "15672:15672"
volumes:
    pgdata:
