# Generated by Django 4.1 on 2022-10-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=125)),
                ("full_name", models.TextField()),
                ("args", models.TextField(blank=True, null=True)),
                ("kwargs", models.TextField(blank=True, null=True)),
                ("exception_class", models.TextField()),
                ("exception_msg", models.TextField()),
                ("traceback", models.TextField(blank=True, null=True)),
                ("celery_task_id", models.CharField(max_length=36)),
                ("failures", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
    ]
