# Generated by Django 4.1 on 2022-10-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="processed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
