# Generated by Django 4.1 on 2022-10-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_page_processed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="stats",
            field=models.JSONField(null=True),
        ),
    ]
