# Generated by Django 4.1 on 2022-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_page_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
