# Generated by Django 4.1 on 2022-10-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagelink",
            name="rel",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pagelink",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
